# Generated by Django 5.2 on 2025-07-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100, unique=True)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('condemning_dia', models.CharField(max_length=100)),
                ('last_shop_issue_size', models.CharField(max_length=100)),
                ('tread_diameter_new', models.CharField(max_length=100)),
                ('wheel_gauge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_guide', models.CharField(max_length=100)),
                ('bogie_frame_condition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolster_suspension_bracket', models.CharField(max_length=100)),
                ('lower_spring_seat', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogie_checksheet', to='api.bogiechecksheetform')),
            ],
        ),
        migrations.CreateModel(
            name='BmbcChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusting_tube', models.CharField(max_length=100)),
                ('cylinder_body', models.CharField(max_length=100)),
                ('piston_trunnion', models.CharField(max_length=100)),
                ('plunger_spring', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmbc_checksheet', to='api.bogiechecksheetform')),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_no', models.CharField(max_length=100)),
                ('date_of_ioh', models.DateField()),
                ('deficit_components', models.TextField()),
                ('incoming_div_and_date', models.CharField(max_length=100)),
                ('maker_year_built', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogie_details', to='api.bogiechecksheetform')),
            ],
        ),
    ]
